# yml file for Appveyor
# Based of Reference at: https://www.appveyor.com/docs/appveyor-yml/
#
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.0-alpha+{branch}.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# set clone depth
clone_depth: 50

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

#---------------------------------#
#    Run Msys2-build commands     #
#---------------------------------#

init:
  - PATH C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%

install:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh installdeps

build_script:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh build

test_script:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh doctest
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh tests

after_test:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh clean
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh bundle


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'out\pkgs\*'
  - path: 'out\bundles\*'
