language: c++

compiler:
  - gcc

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - g++
      - gettext
      - intltool
      - gir1.2-gtk-3.0
      - libgtk-3-dev
      - libjson-c-dev
      - liblcms2-dev
      - libpng12-dev
      - python-dev
      - python3-dev
      - python-gi-dev
      - python-gi-cairo
      - python3-gi-cairo
      - python-nose
      - python3-nose
      - python-numpy
      - python3-numpy
      - python-setuptools
      - python3-setuptools
      - swig
      - swig3.0
      - git

before_script:
    - git clone https://github.com/mypaint/libmypaint
    - cd libmypaint
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - sudo rm -fr libmypaint

    - git clone https://github.com/mypaint/mypaint-brushes
    - cd mypaint-brushes
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - sudo rm -fr mypaint-brushes

script:
    - which python
    - python -m this
    - python --version
    - python setup.py build
    - python setup.py nosetests --tests lib
    - python setup.py test
    - sudo python setup.py managed_install
    - sudo python setup.py managed_uninstall
    - sudo python setup.py install --root=/app/ --prefix=.
    - bash -ex appimage/appimage.sh || true
    - which python3
    - python3 -m this
    - python3 --version
    - python3 setup.py build_ext --swig=/usr/bin/swig3.0
    - python3 setup.py build
    - python3 setup.py nosetests --tests lib
    - python3 setup.py clean --all
    - sudo python3 setup.py managed_install
    - sudo python3 setup.py managed_uninstall
