language: generic

compiler:
    - gcc

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - g++
      - gettext
      - intltool
      - gir1.2-gtk-3.0
      - libgtk-3-dev
      - libjson-c-dev
      - liblcms2-dev
      - libpng12-dev
      - python-dev
      - python-gi-dev
      - python-gi-cairo
      - python-nose
      - python-numpy
      - scons
      - swig
      - git

before_script:
    - git clone https://github.com/mypaint/libmypaint
    - cd libmypaint
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - sudo rm -fr libmypaint

script:
    - scons
    - nosetests --with-doctest lib
    - tests/run_all_basic_tests.sh
    - sudo scons prefix=/app install
    - bash -ex appimage/appimage.sh || true
